version: '3'
services:
  grc_api:
    image: goodreadsclone/api
    container_name: grc_api
    build:
      context: ./API
    depends_on:
      - grc_sql_server
    networks: 
      - net
    ports:
      - "5000:80"
  
  grc_sql_server:
    image: goodreadsclone/sql_server
    container_name: grc_sql_server
    build:
      context: ./DB
    networks: 
      - net
    ports:
      - "1433:1433"

networks:
  net:
    driver: bridge